[build]
  command = "node build-config.js"
  publish = "."

[[redirects]]
  from = "/worker"
  to = "/工厂点餐_工人版_v2.html"
  status = 200

[[redirects]]
  from = "/kitchen"
  to = "/工厂点餐_餐馆视图_v2.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/工厂点餐_文员后台_v2.html"
  status = 200
